export default {
  HOME: '/',
  ABOUT: '/about',
  HISTORY: '/history',
  REGIONALISM: '/regionalism',
  TRANSLATOR: '/translator',
  TUTORIAL: '/tutorial',
  DICTIONARY: '/dictionary',
  DICTIONARY_PLAYER: '/dictionary-player',
  RECORDERAREA: '/recorder-area',
  DOMAIN: '/domain',
  ONBOARDING: '/onboarding',
  SIGNALCAPTURE: '/signal-capture',
  CUSTOMIZATION: '/customization',
};
