// eslint-disable-next-line no-shadow
export enum PlayerKeys {
  PLAYER_MANAGER = 'PlayerManager',
  PLAY_NOW = 'playNow',
  STOP_ALL = 'stopAll',
  SET_PAUSE_STATE = 'setPauseState',
  CHANGE_AVATAR = 'Change',
  SET_SUBTITLE_STATE = 'setSubtitlesState',
  SET_URL = 'setURL',
  INIT_RANDOM_ANIMATION = 'initRandomAnimationsProcess',
  SET_BASE_URL = 'setBaseUrl',
  SET_SLIDER = 'setSlider',
  SEND_REVIEW = 'sendReview',
  CUSTOMIZATION_BRIDGE = 'CustomizationBridge',
  APPLY_JSON = 'ApplyJSON',
  PLAY_WELCOME = 'playWellcome',
  EMOTION_BRIDGE = 'EmotionBridge',
  APPLY_DEFAULT_EMOTION = 'ApplyDefaultEmotion',
  APPLY_HAPPY_EMOTION = 'ApplyHappyEmotion',
  APPLY_SAD_EMOTION = 'ApplySadEmotion',
  APPLY_ANGRY_EMOTION = 'ApplyAngryEmotion',
  APPLY_DISGUST_EMOTION = 'ApplyDisgustEmotion',
  APPLY_FEAR_EMOTION = 'ApplyFearEmotion',
  APPLY_SURPRISE_EMOTION = 'ApplySurpriseEmotion',
  SET_SENTIMENT_ANALYSIS = 'SetSentimentAnalysis',
}
